// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

// 1- enocontrar a sequencia até 4000000
// 2- percorrer a lista encontrada e ver os pares
// 3- somar os numeros pares

// 1
var array = [1, 2];
var valor = 3;
var i = 3;

while (valor <= 4000000) {
    array.push(valor);
    valor = array[i - 1] + array[i - 2];
    i++
}
// 2
var pares = [];
for (var j = 0; j < array.length; j++) {
    if (array[j] % 2 === 0) {
        pares.push(array[j]);
    }
}
// 3
var soma = 0;
for (var k = 0; k < pares.length; k++) {
    soma = soma + pares[k];
}

console.log(soma);
// var soma = 0
//soma += array[j];

